kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta
metadata:
  name: client-admin-crb
subjects:
- kind: User
  name: client
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
