apiVersion: 0.3.0
environments:
  cdk:
    destination:
      namespace: default
      server: https://10.93.140.123:6443
    k8sVersion: v1.11.5
    path: cdk
  default:
    destination:
      namespace: default
      server: https://10.93.140.123:6443
    k8sVersion: v1.11.5
    path: default
kind: ksonnet.io/app
name: kf-micdoher
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/google/kubeflow/tree/master/kubeflow
version: 0.0.1
