apiVersion: v1
kind: Service
metadata:
  name: hold-pg-db-lb-svc
  labels:
    app: hold-pg-db-lb-svc
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: hold-pg-db
