apiVersion: v1
kind: Service
metadata:
  name: hold-core-lb-svc
  labels:
    app: hold-core-lb-svc
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: hold-core
