apiVersion: v1
kind: Service
metadata:
  name: hold-pg-db-svc
  labels:
    app: hold-pg-db-svc
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30002
    protocol: TCP
  selector:
    app: hold-pg-db
